/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_ComAtListBtn from "./UI_ComAtListBtn";
import UI_IcoItem from "./UI_IcoItem";
import UI_HeadPlayer from "./UI_HeadPlayer";
import UI_SocketMsgDlg from "./UI_SocketMsgDlg";
import UI_MsgDlg from "./UI_MsgDlg";
import UI_BuyClothDlg from "./UI_BuyClothDlg";
import UI_GetGiftRewardDlg from "./UI_GetGiftRewardDlg";
import UI_BuyClothDlg2 from "./UI_BuyClothDlg2";
import UI_CompBubbleRight from "./UI_CompBubbleRight";
import UI_CompBubbleLeft from "./UI_CompBubbleLeft";
import UI_ChatRedNum from "./UI_ChatRedNum";
import UI_BuyClothDlg3 from "./UI_BuyClothDlg3";
import UI_CompFlyItem from "./UI_CompFlyItem";
import UI_UserLvlLabel from "./UI_UserLvlLabel";
import UI_GainTipTxt from "./UI_GainTipTxt";
import UI_GainTipTxtItem from "./UI_GainTipTxtItem";
import UI_Comp_ShareBtn from "./UI_Comp_ShareBtn";
import UI_RewardPreview from "./UI_RewardPreview";
import UI_ShareLimitEnter from "./UI_ShareLimitEnter";
import UI_CompVipDesc from "./UI_CompVipDesc";
import UI_PlayerMinisterQuaIcon from "./UI_PlayerMinisterQuaIcon";
import UI_ZhiGouLimitComp1 from "./UI_ZhiGouLimitComp1";
import UI_BaseFrame from "./UI_BaseFrame";
import UI_UserDiyHeadIconMask from "./UI_UserDiyHeadIconMask";
import UI_RankInfoViewComp from "./UI_RankInfoViewComp";
import UI_AvatarGardenRoleCom from "./UI_AvatarGardenRoleCom";
import UI_MinisterQuaIcon from "./UI_MinisterQuaIcon";
import UI_IcoItemWithName from "./UI_IcoItemWithName";
import UI_IconItem80 from "./UI_IconItem80";
import UI_GainTip from "./UI_GainTip";
import UI_FriendnessTip from "./UI_FriendnessTip";
import UI_NewStoryTtile from "./UI_NewStoryTtile";
import UI_ClothStyleCom from "./UI_ClothStyleCom";
import UI_AvatarCom from "./UI_AvatarCom";
import UI_TitleComp from "./UI_TitleComp";
import UI_BuyItemDlg from "./UI_BuyItemDlg";
import UI_Comp_Idtt from "./UI_Comp_Idtt";
import UI_Comp_Chat from "./UI_Comp_Chat";
import UI_CompPlayerHalf from "./UI_CompPlayerHalf";
import UI_CompHeader from "./UI_CompHeader";
import UI_GetRewardItem from "./UI_GetRewardItem";
import UI_AvatarBodyCom from "./UI_AvatarBodyCom";
import UI_Wait from "./UI_Wait";
import UI_AntiqueImg from "./UI_AntiqueImg";
import UI_AntiqueAdd from "./UI_AntiqueAdd";
import UI_CompShowHurt from "./UI_CompShowHurt";
import UI_BuyClothDlg4 from "./UI_BuyClothDlg4";
import UI_HelpDlg from "./UI_HelpDlg";
import UI_UserDiyHeadIcon from "./UI_UserDiyHeadIcon";
import UI_MsgTips from "./UI_MsgTips";
import UI_RedCom from "./UI_RedCom";
import UI_TrySearchResult from "./UI_TrySearchResult";
import UI_UserExpBar from "./UI_UserExpBar";
import UI_AntiqueName from "./UI_AntiqueName";
import UI_IcoShowNameItem from "./UI_IcoShowNameItem";
import UI_ComVipBtn from "./UI_ComVipBtn";
import UI_CompRuleBuff from "./UI_CompRuleBuff";
import UI_HelpDlgInfo from "./UI_HelpDlgInfo";
import UI_CompAdoHeadMask from "./UI_CompAdoHeadMask";
import UI_GetRewardDlg from "./UI_GetRewardDlg";
import UI_ResItem from "./UI_ResItem";
import UI_RewardPreviewItem from "./UI_RewardPreviewItem";
import UI_ZhiGouLimitComp from "./UI_ZhiGouLimitComp";
import UI_CompMateHalf from "./UI_CompMateHalf";
import UI_CompRes from "./UI_CompRes";
import UI_CompResTip from "./UI_CompResTip";
import UI_CompScroll from "./UI_CompScroll";
import UI_CompMinisterBody from "./UI_CompMinisterBody";
import UI_Act from "./UI_Act";
import UI_ActBtn from "./UI_ActBtn";
import UI_HelpDlgInfoItem from "./UI_HelpDlgInfoItem";
import UI_MsgTipsCom from "./UI_MsgTipsCom";
import UI_TaskAchReach from "./UI_TaskAchReach";
import UI_Container from "./UI_Container";

import * as fgui from "fairygui-cc";
export class baseBinder {

	constructor(){
		let self = this;
		self.bindAll();
	}

	private bindAll():void {
		let self = this;

		fgui.UIObjectFactory.setExtension(UI_ComAtListBtn.URL, UI_ComAtListBtn);
		fgui.UIObjectFactory.setExtension(UI_IcoItem.URL, UI_IcoItem);
		fgui.UIObjectFactory.setExtension(UI_HeadPlayer.URL, UI_HeadPlayer);
		fgui.UIObjectFactory.setExtension(UI_SocketMsgDlg.URL, UI_SocketMsgDlg);
		fgui.UIObjectFactory.setExtension(UI_MsgDlg.URL, UI_MsgDlg);
		fgui.UIObjectFactory.setExtension(UI_BuyClothDlg.URL, UI_BuyClothDlg);
		fgui.UIObjectFactory.setExtension(UI_GetGiftRewardDlg.URL, UI_GetGiftRewardDlg);
		fgui.UIObjectFactory.setExtension(UI_BuyClothDlg2.URL, UI_BuyClothDlg2);
		fgui.UIObjectFactory.setExtension(UI_CompBubbleRight.URL, UI_CompBubbleRight);
		fgui.UIObjectFactory.setExtension(UI_CompBubbleLeft.URL, UI_CompBubbleLeft);
		fgui.UIObjectFactory.setExtension(UI_ChatRedNum.URL, UI_ChatRedNum);
		fgui.UIObjectFactory.setExtension(UI_BuyClothDlg3.URL, UI_BuyClothDlg3);
		fgui.UIObjectFactory.setExtension(UI_CompFlyItem.URL, UI_CompFlyItem);
		fgui.UIObjectFactory.setExtension(UI_UserLvlLabel.URL, UI_UserLvlLabel);
		fgui.UIObjectFactory.setExtension(UI_GainTipTxt.URL, UI_GainTipTxt);
		fgui.UIObjectFactory.setExtension(UI_GainTipTxtItem.URL, UI_GainTipTxtItem);
		fgui.UIObjectFactory.setExtension(UI_Comp_ShareBtn.URL, UI_Comp_ShareBtn);
		fgui.UIObjectFactory.setExtension(UI_RewardPreview.URL, UI_RewardPreview);
		fgui.UIObjectFactory.setExtension(UI_ShareLimitEnter.URL, UI_ShareLimitEnter);
		fgui.UIObjectFactory.setExtension(UI_CompVipDesc.URL, UI_CompVipDesc);
		fgui.UIObjectFactory.setExtension(UI_PlayerMinisterQuaIcon.URL, UI_PlayerMinisterQuaIcon);
		fgui.UIObjectFactory.setExtension(UI_ZhiGouLimitComp1.URL, UI_ZhiGouLimitComp1);
		fgui.UIObjectFactory.setExtension(UI_BaseFrame.URL, UI_BaseFrame);
		fgui.UIObjectFactory.setExtension(UI_UserDiyHeadIconMask.URL, UI_UserDiyHeadIconMask);
		fgui.UIObjectFactory.setExtension(UI_RankInfoViewComp.URL, UI_RankInfoViewComp);
		fgui.UIObjectFactory.setExtension(UI_AvatarGardenRoleCom.URL, UI_AvatarGardenRoleCom);
		fgui.UIObjectFactory.setExtension(UI_MinisterQuaIcon.URL, UI_MinisterQuaIcon);
		fgui.UIObjectFactory.setExtension(UI_IcoItemWithName.URL, UI_IcoItemWithName);
		fgui.UIObjectFactory.setExtension(UI_IconItem80.URL, UI_IconItem80);
		fgui.UIObjectFactory.setExtension(UI_GainTip.URL, UI_GainTip);
		fgui.UIObjectFactory.setExtension(UI_FriendnessTip.URL, UI_FriendnessTip);
		fgui.UIObjectFactory.setExtension(UI_NewStoryTtile.URL, UI_NewStoryTtile);
		fgui.UIObjectFactory.setExtension(UI_ClothStyleCom.URL, UI_ClothStyleCom);
		fgui.UIObjectFactory.setExtension(UI_AvatarCom.URL, UI_AvatarCom);
		fgui.UIObjectFactory.setExtension(UI_TitleComp.URL, UI_TitleComp);
		fgui.UIObjectFactory.setExtension(UI_BuyItemDlg.URL, UI_BuyItemDlg);
		fgui.UIObjectFactory.setExtension(UI_Comp_Idtt.URL, UI_Comp_Idtt);
		fgui.UIObjectFactory.setExtension(UI_Comp_Chat.URL, UI_Comp_Chat);
		fgui.UIObjectFactory.setExtension(UI_CompPlayerHalf.URL, UI_CompPlayerHalf);
		fgui.UIObjectFactory.setExtension(UI_CompHeader.URL, UI_CompHeader);
		fgui.UIObjectFactory.setExtension(UI_GetRewardItem.URL, UI_GetRewardItem);
		fgui.UIObjectFactory.setExtension(UI_AvatarBodyCom.URL, UI_AvatarBodyCom);
		fgui.UIObjectFactory.setExtension(UI_Wait.URL, UI_Wait);
		fgui.UIObjectFactory.setExtension(UI_AntiqueImg.URL, UI_AntiqueImg);
		fgui.UIObjectFactory.setExtension(UI_AntiqueAdd.URL, UI_AntiqueAdd);
		fgui.UIObjectFactory.setExtension(UI_CompShowHurt.URL, UI_CompShowHurt);
		fgui.UIObjectFactory.setExtension(UI_BuyClothDlg4.URL, UI_BuyClothDlg4);
		fgui.UIObjectFactory.setExtension(UI_HelpDlg.URL, UI_HelpDlg);
		fgui.UIObjectFactory.setExtension(UI_UserDiyHeadIcon.URL, UI_UserDiyHeadIcon);
		fgui.UIObjectFactory.setExtension(UI_MsgTips.URL, UI_MsgTips);
		fgui.UIObjectFactory.setExtension(UI_RedCom.URL, UI_RedCom);
		fgui.UIObjectFactory.setExtension(UI_TrySearchResult.URL, UI_TrySearchResult);
		fgui.UIObjectFactory.setExtension(UI_UserExpBar.URL, UI_UserExpBar);
		fgui.UIObjectFactory.setExtension(UI_AntiqueName.URL, UI_AntiqueName);
		fgui.UIObjectFactory.setExtension(UI_IcoShowNameItem.URL, UI_IcoShowNameItem);
		fgui.UIObjectFactory.setExtension(UI_ComVipBtn.URL, UI_ComVipBtn);
		fgui.UIObjectFactory.setExtension(UI_CompRuleBuff.URL, UI_CompRuleBuff);
		fgui.UIObjectFactory.setExtension(UI_HelpDlgInfo.URL, UI_HelpDlgInfo);
		fgui.UIObjectFactory.setExtension(UI_CompAdoHeadMask.URL, UI_CompAdoHeadMask);
		fgui.UIObjectFactory.setExtension(UI_GetRewardDlg.URL, UI_GetRewardDlg);
		fgui.UIObjectFactory.setExtension(UI_ResItem.URL, UI_ResItem);
		fgui.UIObjectFactory.setExtension(UI_RewardPreviewItem.URL, UI_RewardPreviewItem);
		fgui.UIObjectFactory.setExtension(UI_ZhiGouLimitComp.URL, UI_ZhiGouLimitComp);
		fgui.UIObjectFactory.setExtension(UI_CompMateHalf.URL, UI_CompMateHalf);
		fgui.UIObjectFactory.setExtension(UI_CompRes.URL, UI_CompRes);
		fgui.UIObjectFactory.setExtension(UI_CompResTip.URL, UI_CompResTip);
		fgui.UIObjectFactory.setExtension(UI_CompScroll.URL, UI_CompScroll);
		fgui.UIObjectFactory.setExtension(UI_CompMinisterBody.URL, UI_CompMinisterBody);
		fgui.UIObjectFactory.setExtension(UI_Act.URL, UI_Act);
		fgui.UIObjectFactory.setExtension(UI_ActBtn.URL, UI_ActBtn);
		fgui.UIObjectFactory.setExtension(UI_HelpDlgInfoItem.URL, UI_HelpDlgInfoItem);
		fgui.UIObjectFactory.setExtension(UI_MsgTipsCom.URL, UI_MsgTipsCom);
		fgui.UIObjectFactory.setExtension(UI_TaskAchReach.URL, UI_TaskAchReach);
		fgui.UIObjectFactory.setExtension(UI_Container.URL, UI_Container);

		if(!self['bindExt']) console.error('未实现bindExt');
		self['bindExt']();
	}
}